// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCySOWonfHFbyFqgi0H3k82XqnQdVNAKQ8',
    appId: '1:564279025477:web:f5890e1f0398366468282c',
    messagingSenderId: '564279025477',
    projectId: 'fluttergram-225ca',
    authDomain: 'fluttergram-225ca.firebaseapp.com',
    storageBucket: 'fluttergram-225ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSpX2MDokUQUSL27pirxjmkD6I2s1BJZw',
    appId: '1:564279025477:android:0c6a6fc655a389de68282c',
    messagingSenderId: '564279025477',
    projectId: 'fluttergram-225ca',
    storageBucket: 'fluttergram-225ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbfEqvMHYVVH-iMd8o1WOhvAvRyWWu8sc',
    appId: '1:564279025477:ios:ee67b6f0c23ecf1668282c',
    messagingSenderId: '564279025477',
    projectId: 'fluttergram-225ca',
    storageBucket: 'fluttergram-225ca.appspot.com',
    iosClientId: '564279025477-4uafnusduk9t49eluj3c6van4dindf1b.apps.googleusercontent.com',
    iosBundleId: 'com.shinjoo.instagram',
  );
}
